name: Publish Web Client to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'web-client/**'
      - '.github/workflows/publish-client.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      # Standard clean installation for workspace syncing
      - name: Install dependencies
        run: npm ci

      - name: Build Web Client Library
        run: cd web-client && npm run build:lib

      - name: Publish Package
        run: cd web-client && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
